Repository MDAnalysis/mdacli, pull requests merged in 2021-11, with the labels that each got.

#62 Usage added
  README.rst
  docs/AUTHORS.rst
  docs/rst/conf.py
  docs/rst/index.rst
  docs/rst/installation.rst
  docs/rst/philosophy.rst
  docs/rst/usage.rst
Labels: documentation, hacktoberfest-accepted

#64 Prepare for downstream usage
  docs/rst/api.rst
  docs/rst/api/cli.rst
  docs/rst/api/colors.rst
  docs/rst/api/libcli.rst
  docs/rst/api/logger.rst
  docs/rst/api/save.rst
  docs/rst/api/utils.rst
  docs/rst/contributing.rst
  docs/rst/index.rst
  docs/rst/reference/index.rst
  docs/rst/reference/mdacli.rst
  setup.py
  src/mdacli/__init__.py
  src/mdacli/__main__.py
  src/mdacli/cli.py
  src/mdacli/libcli.py
  src/mdacli/logger.py
  src/mdacli/utils.py
  tests/test_cli.py
  tests/test_libcli.py
  tests/test_utils.py
Labels: documentation, enhancement, hacktoberfest-accepted

#61 Prepare v0.1.0 release
  .bumpversion.cfg
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/py37.yml
  .github/workflows/py38.yml
  .github/workflows/py39.yml
  .github/workflows/version-bump-and-package.yml
  README.rst
  docs/CHANGELOG.rst
  docs/CONTRIBUTING.rst
  docs/PULLREQUEST.rst
  docs/rst/api.rst
  docs/rst/api/cli.rst
  docs/rst/api/colors.rst
  docs/rst/api/libcli.rst
  docs/rst/api/logger.rst
  docs/rst/api/save.rst
  docs/rst/api/utils.rst
  docs/rst/conf.py
  docs/rst/contributing.rst
  docs/rst/installation.rst
  docs/rst/philosophy.rst
  docs/rst/usage.rst
  setup.py
  src/mdacli/cli.py
  tox.ini
Labels: enhancement, hacktoberfest-accepted

#66 Corrects bumps subtitle in changelog
  .bumpversion.cfg
  .github/workflows/version-bump-and-package.yml
  docs/CHANGELOG.rst
  docs/CONTRIBUTING.rst
Labels: bug
